### ISSUE TITLE
Mongo error

### ISSUE THREAD

**Issue by im281** [Miksus/red-bird#44]
need to comment the json["_id"] out for it to work as self.id_field is none and likely the same for all the operations

def item_to_data(self, item:BaseModel):
        json = self.item_to_dict(item, exclude_unset=False)
        # Rename whatever is as id_field to _id
        #json["_id"] = json.pop(self.id_field)
        return json

**Comment by joaoheusi** [comment]
Are there any workarounds for the errors happening in MongoRepo?

`Fatal error encountered. Shutting down...
Traceback (most recent call last):
  File "C:\Users\joaoh\projects\airgate\.venv\Lib\site-packages\redbird\templates.py", line 68, in last
    return self.repo.query_read_last(self.query_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joaoh\projects\airgate\.venv\Lib\site-packages\redbird\templates.py", line 309, in query_read_last
    raise NotImplementedError("Read using first not implemented.")
NotImplementedError: Read using first not implemented.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joaoh\projects\airgate\.venv\Lib\site-packages\redbird\templates.py", line 15, in query
    value = self._get_last_action_from_log(action, logger)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joaoh\projects\airgate\.venv\Lib\site-packages\rocketry\core\task.py", line 1266, in _get_last_action_from_log
    record = logger.get_latest(action=action)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joaoh\projects\airgate\.venv\Lib\site-packages\rocketry\core\log\adapter.py", line 114, in get_latest
    return self.filter_by(**kwargs).last()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joaoh\projects\airgate\.venv\Lib\site-packages\redbird\templates.py", line 70, in last
    return super().last()
           ^^^^^^^^^^^^^^
  File "C:\Users\joaoh\projects\airgate\.venv\Lib\site-packages\redbird\base.py", line 57, in last
    for item in self.query():
  File "C:\Users\joaoh\projects\airgate\.venv\Lib\site-packages\redbird\templates.py", line 19, in query
    yield self.repo.data_to_item(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joaoh\projects\airgate\.venv\Lib\site-packages\redbird\repos\mongo.py", line 250, in data_to_item
    return self.model(**json)
           ^^^^^^^^^^^^^^^^^^
TypeError: keywords must be strings`
